export type CapabilityMode = 'native' | 'delegated' | 'constrained';
export type RetrievalMode =
  'calculated_official_api' | 'official_api_live' | 'official_api_lookup' | 'route_only';

export interface CompatibilityCapability {
  compatibility_tool: string;
  olano_tool: string;
  mode: CapabilityMode;
  source: string;
  freshness: string;
  retrieval: RetrievalMode;
  note: string;
}

function capability(
  compatibilityTool: string,
  olanoTool: string,
  mode: CapabilityMode,
  source: string,
  freshness: string,
  retrieval: RetrievalMode,
  note: string,
): CompatibilityCapability {
  return {
    compatibility_tool: compatibilityTool,
    olano_tool: olanoTool,
    mode,
    source,
    freshness,
    retrieval,
    note,
  };
}

const DGS = 'data.gov.sg and the named source agency';
const SINGSTAT = 'SingStat Table Builder API';

export const altronisCompatibilityRegistry: CompatibilityCapability[] = [
  capability(
    'sg_ask',
    'singapore_ask',
    'native',
    'Olano capability catalogue',
    'repository release',
    'route_only',
    'Deterministic recommendation only; it never executes an arbitrary tool.',
  ),
  capability(
    'sg_visualize',
    'insights_visualize_series',
    'native',
    'Caller-provided observations',
    'input-defined',
    'calculated_official_api',
    'Adds text and chart-ready output without sending observations to a third party.',
  ),
  capability(
    'sg_cross_dataset',
    'insights_compare_series',
    'native',
    'Caller-provided observations',
    'input-defined',
    'calculated_official_api',
    'Automatically normalises monthly, quarterly, or annual periods before comparison.',
  ),
  capability(
    'sg_list_datasets',
    'singapore_catalog_list',
    'delegated',
    DGS,
    'metadata-cached',
    'official_api_lookup',
    'Use the richer Olano catalogue tool.',
  ),
  capability(
    'sg_search_datasets',
    'singapore_dataset_search',
    'native',
    'data.gov.sg dataset catalogue API',
    'live catalogue',
    'official_api_lookup',
    'Pages the official catalogue and performs deterministic local text and agency filtering because the documented catalogue endpoint exposes no search query.',
  ),
  capability(
    'sg_dataset_schema',
    'datagov_get_dataset_metadata',
    'delegated',
    'data.gov.sg metadata API',
    'live metadata',
    'official_api_lookup',
    'Direct official metadata lookup.',
  ),
  capability(
    'sg_dataset_query',
    'datagov_list_dataset_rows',
    'delegated',
    'data.gov.sg dataset API',
    'upstream-defined',
    'official_api_lookup',
    'Direct bounded official row retrieval; Olano does not silently download an unbounded dataset.',
  ),

  capability(
    'sg_acra_search_entities',
    'acra_search_entities',
    'delegated',
    'ACRA public entity datasets on data.gov.sg',
    'monthly',
    'official_api_lookup',
    'Searches the 27 official entity shards.',
  ),
  capability(
    'sg_acra_get_entity',
    'acra_get_entity',
    'delegated',
    'ACRA public entity datasets on data.gov.sg',
    'monthly',
    'official_api_lookup',
    'Exact UEN resolution remains subject to public-dataset coverage.',
  ),
  capability(
    'sg_acra_formations_by_ssic',
    'business_formations_compare',
    'constrained',
    'SingStat business formation tables',
    'monthly',
    'calculated_official_api',
    'Uses official formation series by industry; ACRA public entity shards are not a complete historical formation event feed.',
  ),
  capability(
    'sg_hdb_resale_search',
    'hdb_resale_search',
    'delegated',
    'HDB resale registrations on data.gov.sg',
    'monthly',
    'official_api_lookup',
    'Bounded official row search.',
  ),
  capability(
    'sg_hdb_resale_stats',
    'hdb_resale_stats',
    'native',
    'HDB resale registrations on data.gov.sg',
    'monthly',
    'calculated_official_api',
    'Returns median, quartiles, price per square metre and grouped summaries.',
  ),
  capability(
    'sg_coe_latest',
    'coe_latest',
    'native',
    'LTA COE bidding results on data.gov.sg',
    'each bidding exercise',
    'calculated_official_api',
    'Adds demand, success, utilisation and prior-premium changes.',
  ),
  capability(
    'sg_coe_history',
    'coe_history',
    'native',
    'LTA COE bidding results on data.gov.sg',
    'each bidding exercise',
    'calculated_official_api',
    'Bounded category-specific history.',
  ),
  capability(
    'sg_coe_demand_supply',
    'coe_demand_supply',
    'native',
    'LTA COE bidding results on data.gov.sg',
    'each bidding exercise',
    'calculated_official_api',
    'Calculates bid-to-quota, excess bids, success and utilisation.',
  ),
  capability(
    'sg_moe_search_schools',
    'moe_schools_search',
    'delegated',
    'MOE schools on data.gov.sg',
    'upstream-defined',
    'official_api_lookup',
    'Curated official school search.',
  ),
  capability(
    'sg_moe_school_by_name',
    'moe_schools_search',
    'delegated',
    'MOE schools on data.gov.sg',
    'upstream-defined',
    'official_api_lookup',
    'Use an exact school name as the query.',
  ),
  capability(
    'sg_moe_schools_near',
    'moe_schools_near',
    'native',
    'SLA OneMap education themes, with MOE dataset attribution',
    'upstream-defined',
    'calculated_official_api',
    'Uses official OneMap coordinates and true haversine distance rather than a postal-prefix proximity proxy; requires ONEMAP_TOKEN.',
  ),
  capability(
    'sg_hdb_carpark_lookup',
    'hdb_carparks_search',
    'delegated',
    'HDB carpark information on data.gov.sg',
    'upstream-defined',
    'official_api_lookup',
    'Curated official carpark search.',
  ),
  capability(
    'sg_hdb_carparks_by_address',
    'hdb_carparks_search',
    'delegated',
    'HDB carpark information on data.gov.sg',
    'upstream-defined',
    'official_api_lookup',
    'Pass an address fragment as the search query.',
  ),
  capability(
    'sg_hdb_carparks_by_type',
    'hdb_carparks_search',
    'delegated',
    'HDB carpark information on data.gov.sg',
    'upstream-defined',
    'official_api_lookup',
    'Search the official type values and inspect metadata first when needed.',
  ),
  capability(
    'sg_gdp_latest',
    'gdp_growth_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Curated GDP growth observations.',
  ),
  capability(
    'sg_gdp_history',
    'gdp_growth_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Bounded official history.',
  ),
  capability(
    'sg_gdp_industry_compare',
    'gdp_industry_compare',
    'native',
    DGS,
    'quarterly',
    'calculated_official_api',
    'Ranks all numeric official industry rows for an explicit quarter and preserves the matched source column.',
  ),
  capability(
    'sg_cpi_latest',
    'cpi_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Curated official CPI lookup.',
  ),
  capability(
    'sg_cpi_history',
    'cpi_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official wide-series rows preserve the full published history.',
  ),
  capability(
    'sg_cpi_yoy',
    'cpi_yoy',
    'native',
    DGS,
    'monthly',
    'calculated_official_api',
    'Calculates same-month annual change rather than comparing adjacent months.',
  ),
  capability(
    'sg_median_income_lookup',
    'median_income_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Curated MOM income lookup.',
  ),
  capability(
    'sg_median_income_history',
    'median_income_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official published income history.',
  ),
  capability(
    'sg_employment_by_sector',
    'employment_sector_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Curated sector row search.',
  ),
  capability(
    'sg_employment_sector_history',
    'employment_sector_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official wide-series history.',
  ),
  capability(
    'sg_employment_growth',
    'employment_growth',
    'native',
    DGS,
    'annual',
    'calculated_official_api',
    'Calculates absolute and percentage annual sector change.',
  ),
  capability(
    'sg_ura_private_txn_latest',
    'ura_private_property_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Curated public transaction search.',
  ),
  capability(
    'sg_ura_private_txn_history',
    'ura_private_property_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Bounded public transaction evidence.',
  ),
  capability(
    'sg_ura_new_sale_pipeline',
    'ura_new_sale_pipeline',
    'native',
    DGS,
    'quarterly',
    'calculated_official_api',
    'Separately sums completed and uncompleted official new-sale units while explicitly warning this is not unsold inventory or a launch forecast.',
  ),
  capability(
    'sg_visitors_latest',
    'visitor_arrivals_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Curated STB visitor-arrival lookup.',
  ),
  capability(
    'sg_visitors_history',
    'visitor_arrivals_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_visitors_top_sources',
    'visitors_top_sources',
    'native',
    DGS,
    'monthly',
    'calculated_official_api',
    'Ranks countries or regions separately and excludes Other Markets aggregates from country ranking.',
  ),
  capability(
    'sg_retail_sales_latest',
    'retail_sales_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Curated Retail Sales Index lookup.',
  ),
  capability(
    'sg_retail_sales_history',
    'retail_sales_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official wide-series history.',
  ),
  capability(
    'sg_retail_sales_yoy',
    'retail_sales_yoy',
    'native',
    DGS,
    'monthly',
    'calculated_official_api',
    'Calculates same-month annual change.',
  ),
  capability(
    'sg_fx_rate',
    'fx_rate',
    'native',
    'MAS exchange rates on data.gov.sg',
    'monthly',
    'calculated_official_api',
    'Normalizes the official per-one or per-100 foreign-currency quote; it is not a tradeable rate.',
  ),
  capability(
    'sg_fx_history',
    'fx_history',
    'native',
    'MAS exchange rates on data.gov.sg',
    'monthly',
    'calculated_official_api',
    'Returns normalized official average-rate history with explicit unit scaling.',
  ),
  capability(
    'sg_fx_basket',
    'fx_basket',
    'native',
    'MAS exchange rates on data.gov.sg',
    'monthly',
    'calculated_official_api',
    'Values explicit foreign-currency amounts in SGD with per-100 scaling handled transparently.',
  ),
  capability(
    'sg_iras_collection',
    'iras_tax_search',
    'delegated',
    'IRAS tax collection on data.gov.sg',
    'annual',
    'official_api_lookup',
    'Official tax collection lookup.',
  ),
  capability(
    'sg_iras_collection_history',
    'iras_tax_search',
    'delegated',
    'IRAS tax collection on data.gov.sg',
    'annual',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_iras_tax_mix',
    'iras_tax_mix',
    'native',
    'IRAS tax collection on data.gov.sg',
    'annual',
    'calculated_official_api',
    'Calculates category shares in the official S$ thousand unit for one financial year.',
  ),
  capability(
    'sg_ecda_search_centres',
    'ecda_childcare_search',
    'delegated',
    DGS,
    'upstream-defined',
    'official_api_lookup',
    'Official ECDA centre search.',
  ),
  capability(
    'sg_ecda_centres_near',
    'ecda_centres_near',
    'native',
    'SLA OneMap kindergarten and childcare themes, with ECDA dataset attribution',
    'upstream-defined',
    'calculated_official_api',
    'Uses official theme coordinates and true haversine distance rather than a postal-prefix proxy; requires ONEMAP_TOKEN.',
  ),
  capability(
    'sg_ecda_vacancy_summary',
    'ecda_vacancy_summary',
    'native',
    DGS,
    'daily/upstream-defined',
    'calculated_official_api',
    'Preserves ECDA categorical Available, Limited and Full values and reports numeric totals only when the source actually publishes numbers.',
  ),
  capability(
    'sg_unemployment_latest',
    'unemployment_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Official MOM unemployment series.',
  ),
  capability(
    'sg_unemployment_history',
    'unemployment_search',
    'delegated',
    DGS,
    'quarterly',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_population_latest',
    'population_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official population indicators.',
  ),
  capability(
    'sg_population_history',
    'population_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_disease_latest',
    'disease_cases_latest',
    'native',
    DGS,
    'frozen at upstream dataset coverage',
    'official_api_lookup',
    'The curated data.gov.sg dataset may be stale; check freshness and current MOH bulletins.',
  ),
  capability(
    'sg_disease_trend',
    'disease_cases_trend',
    'native',
    DGS,
    'frozen at upstream dataset coverage',
    'calculated_official_api',
    'Never presents frozen source data as current.',
  ),
  capability(
    'sg_disease_list',
    'disease_cases_list',
    'native',
    DGS,
    'frozen at upstream dataset coverage',
    'official_api_lookup',
    'Lists actual published disease labels and source-coverage totals while clearly flagging frozen historical coverage.',
  ),
  capability(
    'sg_electricity_latest',
    'electricity_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official EMA electricity generation data.',
  ),
  capability(
    'sg_electricity_history',
    'electricity_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_births_latest',
    'live_births_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official live-birth indicators.',
  ),
  capability(
    'sg_births_history',
    'live_births_search',
    'delegated',
    DGS,
    'monthly',
    'official_api_lookup',
    'Official published history.',
  ),
  capability(
    'sg_crime_latest',
    'crime_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official recorded-crime aggregates.',
  ),
  capability(
    'sg_crime_history',
    'crime_search',
    'delegated',
    DGS,
    'annual',
    'official_api_lookup',
    'Official aggregate history.',
  ),
  capability(
    'sg_crime_compare',
    'crime_compare',
    'native',
    DGS,
    'annual',
    'calculated_official_api',
    'Ranks official series for an explicit year and flags the 2022 reporting break, mixed rate/count units, and aggregate-risk limitation.',
  ),
  capability(
    'sg_tourism_latest',
    'tourism_receipts_search',
    'delegated',
    DGS,
    'frozen at upstream dataset coverage',
    'official_api_lookup',
    'The curated receipts source may be stale; inspect freshness and cross-check current STB data.',
  ),
  capability(
    'sg_tourism_history',
    'tourism_receipts_search',
    'delegated',
    DGS,
    'frozen at upstream dataset coverage',
    'official_api_lookup',
    'Official published history with a visible stale-data constraint.',
  ),
  capability(
    'sg_hawker_search',
    'hawker_centres_search',
    'delegated',
    DGS,
    'upstream-defined',
    'official_api_lookup',
    'Official NEA hawker-centre search.',
  ),
  capability(
    'sg_hawker_stats',
    'hawker_centres_profile',
    'delegated',
    DGS,
    'upstream-defined',
    'calculated_official_api',
    'Profiles official centre fields.',
  ),
  capability(
    'sg_formations_latest',
    'singstat_business_formations_monthly_latest',
    'delegated',
    SINGSTAT,
    'monthly',
    'official_api_live',
    'Official latest SingStat observations.',
  ),
  capability(
    'sg_formations_history',
    'singstat_business_formations_monthly_history',
    'delegated',
    SINGSTAT,
    'monthly',
    'official_api_live',
    'Official bounded SingStat history.',
  ),
  capability(
    'sg_formations_compare',
    'business_formations_compare',
    'native',
    SINGSTAT,
    'monthly',
    'calculated_official_api',
    'Aligns formations and cessations for multiple industries.',
  ),
  capability(
    'sg_formations_monthly',
    'singstat_business_formations_monthly_history',
    'delegated',
    SINGSTAT,
    'monthly',
    'official_api_live',
    'Official formation series.',
  ),
  capability(
    'sg_cessations_monthly',
    'singstat_business_cessations_monthly_history',
    'delegated',
    SINGSTAT,
    'monthly',
    'official_api_live',
    'Official cessation series.',
  ),
  capability(
    'sg_net_formations',
    'business_formations_net',
    'native',
    SINGSTAT,
    'monthly',
    'calculated_official_api',
    'Matches periods and subtracts cessations from formations.',
  ),

  capability(
    'sg_carpark_availability',
    'lta_carpark_availability',
    'delegated',
    'LTA DataMall',
    'live',
    'official_api_live',
    'Requires LTA_DATAMALL_API_KEY.',
  ),
  capability(
    'sg_weather_forecast',
    'weather_two_hour_forecast',
    'delegated',
    'NEA via data.gov.sg',
    'live',
    'official_api_live',
    'Official two-hour forecast.',
  ),
  capability(
    'sg_psi',
    'weather_air_quality',
    'delegated',
    'NEA via data.gov.sg',
    'live',
    'official_api_live',
    'Official PSI observations.',
  ),
  capability(
    'sg_rainfall',
    'weather_rainfall',
    'delegated',
    'NEA via data.gov.sg',
    'live',
    'official_api_live',
    'Official station rainfall observations.',
  ),
  capability(
    'sg_air_temperature',
    'weather_temperature',
    'delegated',
    'NEA via data.gov.sg',
    'live',
    'official_api_live',
    'Official station temperature observations.',
  ),
  capability(
    'sg_dengue_clusters',
    'dengue_clusters_search',
    'delegated',
    'NEA on data.gov.sg',
    'current dataset',
    'official_api_lookup',
    'Official cluster records.',
  ),
  capability(
    'sg_household_income',
    'singstat_household_income_history',
    'delegated',
    SINGSTAT,
    'annual',
    'official_api_live',
    'Official household income indicators.',
  ),
  capability(
    'sg_wages',
    'singstat_wages_history',
    'delegated',
    SINGSTAT,
    'quarterly or annual by series',
    'official_api_live',
    'Official nominal earnings indicators.',
  ),
  capability(
    'sg_deaths',
    'singstat_deaths_history',
    'delegated',
    SINGSTAT,
    'annual',
    'official_api_live',
    'Official deaths and rates.',
  ),
  capability(
    'sg_marriages',
    'singstat_marriages_history',
    'delegated',
    SINGSTAT,
    'annual',
    'official_api_live',
    'Official marriage indicators.',
  ),
  capability(
    'sg_divorces',
    'singstat_divorces_history',
    'delegated',
    SINGSTAT,
    'annual',
    'official_api_live',
    'Official divorce indicators.',
  ),
  capability(
    'sg_trade',
    'singstat_merchandise_trade_history',
    'delegated',
    SINGSTAT,
    'monthly or annual by series',
    'official_api_live',
    'Official merchandise trade indicators.',
  ),
  capability(
    'sg_labour_force',
    'singstat_labour_force_history',
    'delegated',
    SINGSTAT,
    'annual',
    'official_api_live',
    'Official resident labour-force participation indicators.',
  ),
];

export const nativeCompatibilityAliases = new Set([
  'sg_ask',
  'sg_visualize',
  'sg_cross_dataset',
  'sg_search_datasets',
  'sg_moe_schools_near',
  'sg_ecda_centres_near',
  'sg_ecda_vacancy_summary',
  'sg_gdp_industry_compare',
  'sg_disease_latest',
  'sg_disease_trend',
  'sg_disease_list',
  'sg_crime_compare',
  'sg_hdb_resale_stats',
  'sg_coe_latest',
  'sg_coe_history',
  'sg_coe_demand_supply',
  'sg_cpi_yoy',
  'sg_employment_growth',
  'sg_retail_sales_yoy',
  'sg_formations_compare',
  'sg_net_formations',
  'sg_fx_rate',
  'sg_fx_history',
  'sg_fx_basket',
  'sg_iras_tax_mix',
  'sg_visitors_top_sources',
  'sg_ura_new_sale_pipeline',
]);

export function validateCompatibilityRegistry(): void {
  const names = altronisCompatibilityRegistry.map((item) => item.compatibility_tool);
  if (names.length !== 87)
    throw new Error(`Expected 87 compatibility capabilities, received ${names.length}.`);
  const unique = new Set(names);
  if (unique.size !== names.length)
    throw new Error('Compatibility capability names must be unique.');
  const nativeNames = altronisCompatibilityRegistry
    .filter((item) => item.mode === 'native')
    .map((item) => item.compatibility_tool);
  const missingNativeHandlers = nativeNames.filter((name) => !nativeCompatibilityAliases.has(name));
  if (missingNativeHandlers.length) {
    throw new Error(
      `Native compatibility capabilities must have executable alias handlers: ${missingNativeHandlers.join(', ')}.`,
    );
  }
  const routeOnly = altronisCompatibilityRegistry.filter(
    (item) => item.retrieval === 'route_only' && item.compatibility_tool !== 'sg_ask',
  );
  if (routeOnly.length) {
    throw new Error(
      `Only the recommendation-only sg_ask capability may be route-only: ${routeOnly.map((item) => item.compatibility_tool).join(', ')}.`,
    );
  }
}

validateCompatibilityRegistry();
